stages:
  - test

test:
    stage: test
    image: maven:3.3.9-jdk-8
    script:
    - echo "Test DEMO app"
    - mvn test && mvn jacoco:report
    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", 
instructions, "instructions covered"; print 100*covered/instructions, "% 
covered" }' target/site/jacoco/jacoco.csv
    coverage: \d+.\d+ \% covered
