image: maven:3-jdk-11

stages:
    - build
    - test
    - checkstyle

build_edream:
  stage: build
  script: 
    - echo "Building DEMO app"
    - mvn clean install

test_edream:
    stage: test
    script:
    - echo "Test DEMO app"
    - mvn test && mvn jacoco:report
    coverage: "/Total.*?([0-9]{1,3})%/"

checkstyle_edream:
    stage: checkstyle
    script:
    - echo "Checkstyle DEMO app"
    - mvn checkstyle:check

