image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  
stages:
    - package
    - deploy
  
variables:
    APP_NAME: spring-demo-ds2020
    HEROKU_REGISTRY_LOCATION: registry.heroku.com/spring-demo-ds2020/web
    GITLAB_REGISTRY_LOCATION: gitlab.com/ds_20201/spring-demo/spring-demo-ds2020

build_image:
  image: docker:latest
  services:
  - docker:dind
  stage: package
  script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
    - docker build -t $GITLAB_REGISTRY_LOCATION .
    - docker push $GITLAB_REGISTRY_LOCATION:latest

deploy:
  stage: deploy
  only:
    - docker_production
  script:
    - docker login --username=_ --password=$HEROKU_TOKEN registry.heroku.com
    - docker pull $GITLAB_REGISTRY_LOCATION:latest
    - docker tag $GITLAB_REGISTRY_LOCATION:latest $HEROKU_REGISTRY_LOCATION:latest
    - docker push $HEROKU_REGISTRY_LOCATION:latest
    - docker run --rm -e HEROKU_API_KEY=$HEROKU_TOKEN wingrunr21/alpine-heroku-cli container:release web --app $APP_NAME

