image: docker:latest

before_script:
    - apk --no-cache add curl
    - apk add --no-cache py-pip 
    - pip install docker-compose
    - docker-compose --version

stages:
    - deploy
  
variables:
    APP_NAME: spring-demo-ds2020
    REGISTRY_LOCATION: registry.heroku.com/spring-demo-ds2020/web

deploy:
  stage: deploy
  only:
    - docker_production
  script:
    - docker login --username=_ --password=$HEROKU_TOKEN registry.heroku.com
    - docker build -t $APP_NAME .
    - docker push $REGISTRY_LOCATION
    - docker run --rm -e HEROKU_API_KEY=$HEROKU_TOKEN wingrunr21/alpine-heroku-cli container:release web --app $APP_NAME
    
