stages:
    - package
    - deploy

variables:
  DOCKER_DRIVER: overlay
  
variables:
    APP_NAME: spring-demo-ds2020
    HEROKU_IMAGE: registry.heroku.com/spring-demo-ds2020/web

build_image:
  image: docker:latest
  services:
    - docker:dind
  stage: package
  script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest

deploy:
  image: docker:latest
  services:
    - docker:dind
  stage: deploy
  only:
    - docker_production
  script:
    - docker login --username=_ --password=$HEROKU_TOKEN registry.heroku.com
    - docker pull $CI_REGISTRY_IMAGE:latest
    - docker tag $CI_REGISTRY_IMAGE:latest $HEROKU_IMAGE:latest
    - docker push $HEROKU_IMAGE:latest
    - docker run --rm -e HEROKU_API_KEY=$HEROKU_TOKEN wingrunr21/alpine-heroku-cli container:release web --app $APP_NAME

